import { REGULAR_AERO_PRESS_RECIPE, REGULAR_AERO_PRESS_WITH_KETTLE_RECIPE } from './data'

export * from './model'

export const RECIPES = [
	REGULAR_AERO_PRESS_RECIPE,
	REGULAR_AERO_PRESS_WITH_KETTLE_RECIPE,
]
